### ISSUE TITLE
definamos para que es el template...

### ISSUE THREAD

**Issue by andresxg** [evercoders/Home-template#1]
hola como están, aporto mi sugerencia que el template sea para contener cualquier elemento producido por unity o blender, es decir que dentro de su body exista un contenedor de unity, el resto elementos que componen el template , están en maquetación y a modo de prueba en cuanto al ui y el ux, pues mas nada, hacerle un pull y ver en que se puede aportar,

**Comment by aguja2013** [comment]
Me parece genial la integración con Unity. Qué sería el contenedor de Unity? una demo...? un contenedor 3d...animado?
Se me ocurre un escenario 3d conteniendo un producto Blender

**Comment by slvr** [comment]
si puede ser un demo con web unity player :)

**Comment by aguja2013** [comment]
Definimos un template donde se muestren trabajos hechos en blender dentro de uno o varios contenedores web unity player. Si están de acuerdo cerramos este issue y pasamos a la elaboración del mockup.

**Comment by estebanrfp** [comment]
De acuerdo Agu, buena idea.

**Comment by aguja2013** [comment]
Propongo que para darle fluidez al proyecto, teniendo en cuenta el objetivo principal de práctica de maquetación y trabajo con git - github, hagamos la primera versión con imágenes y dejemos la integración de web unity player para una posterior versión.

**Comment by estebanrfp** [comment]
Si, estoy de acuerdo en hacer un despliegue progresivo y no empezar con elementos avanzados, sobre todo para definir la finalidad de este proyecto que es en definitiva la practica de git para gonzo y poder mejorar el timing de desarrollo en equipo.
