### ISSUE TITLE
Creamos los demás archivos .html, secciones del proyecto como el ejemplo contacto.html

### ISSUE THREAD

**Issue by estebanrfp** [evercoders/Home-template#2]

**Comment by estebanrfp** [comment]
Creados login.html registro.html servicio.html junto con contacto.html.
Dejo abierto este issue, por si creamos mas secciones, si las encuentro en el index.html, yo las descentralizaré si estáis de acuerdo?.

**Comment by aguja2013** [comment]
Ya agregué para mantenimiento y soporte según mockup
0b1822fc99b641a815efd8999c814baa25fef37b

**Comment by estebanrfp** [comment]
Archivos .html creados, se cierra este issue.
