### ISSUE TITLE
Mockup del proyecto. Versión móvil.

### ISSUE THREAD

**Issue by aguja2013** [evercoders/Home-template#3]
La idea es crear un mockup simple del proyecto para versión móvil y escritorio, los contenedores de unity los hacemos con imágenes y dejamos la integración de unity para la siguiente versión.
Subir algo sencillo y lo discutimos en los comentarios de este issue.. Saludos

**Comment by andresxg** [comment]
fff309715bc477db3b910fbacd5d2c96bdff4ddb

**Comment by andresxg** [comment]
los colores no están definidos , pero sugiero que se mantenga la unidad que planteo, siendo de un mismo color todos los elementos que son amarillos y de otro color que contraste  los elementos  restantes , apoyandonos claramente en un tercer color que puede ser un color intermedio

**Comment by aguja2013** [comment]
muy muy muy bueno andrés, copio aquí la imagen también

![untitled-1](https://cloud.githubusercontent.com/assets/9625917/7346476/0be7f926-ecb5-11e4-8c62-96fc8f798f3b.jpg)

**Comment by aguja2013** [comment]
me gustan los colores.
Me parece que el objetivo de este issue está cumplido, voy abrir otro para definir los colores y otro para las fuentes. Definiendo esto daríamos finalizado el primer milestone con vencimiento el jueves.

**Comment by estebanrfp** [comment]
Dejo mi huella desde aquí, como has dicho antes, la onda monocromática me gusta mucho, es original la idea que planteaste. esperaremos al jueves entonces para finalizarlo.
