### ISSUE TITLE
definimos colores

### ISSUE THREAD

**Issue by aguja2013** [evercoders/Home-template#4]
el mockup ya se le han asignado algunos colores, discutir si estamos de acuerdo o incorporamos alguna variación.
![untitled-1](https://cloud.githubusercontent.com/assets/9625917/7346576/3acf6f3e-ecb6-11e4-904f-ce4325ddeae6.jpg)

**Comment by aguja2013** [comment]
Propongo suavizar al negro en un #1d1d1d
![untitled-2](https://cloud.githubusercontent.com/assets/9625917/7347003/6079431e-ecba-11e4-936e-2ef1ff377d4a.png)

**Comment by aguja2013** [comment]
http://paletton.com/palette.php?uid=11T0u0kEf2-r92aqs2i00rwAkr9

**Comment by andresxg** [comment]
estoy de acuerdo con la paleta que propone aguja en el link que envía

**Comment by andresxg** [comment]
#FFEB3B El amarillo
#1d1d1d el negro
# FFFFFF el blanco
