### ISSUE TITLE
Fuentes

### ISSUE THREAD

**Issue by aguja2013** [evercoders/Home-template#5]
Definimos tipografía e iconos

**Comment by aguja2013** [comment]
Podemos dejar las que utilizó gonzo. ¿Cuales son?. Deberíamos decidir si vamos utilizar fuentes nativas, externas(google fonts) o incorporadas al proyecto(font squirrel)

**Comment by aguja2013** [comment]
Aquí dejo 2 tipografías de google fonts
![screen shot 2015-04-28 at 08 22 54](https://cloud.githubusercontent.com/assets/9625917/7368595/132f5082-ed80-11e4-9d66-64ad43d02a4a.png)
![screen shot 2015-04-28 at 08 19 49](https://cloud.githubusercontent.com/assets/9625917/7368596/155748d8-ed80-11e4-805a-34a4af9d1790.png)

**Comment by estebanrfp** [comment]
Incorporadas alproyecto implica el proceso dd selección, mejor las de google?

**Comment by aguja2013** [comment]
las de google más rápido y fácil...   incorporadas al proyecto más opciones para elegir...
Ustedes que prefieren?

**Comment by andresxg** [comment]
es mas laborioso trabajar con una tipografía ajena a las de google? sería interesante ver este template con el juego de esas dos tipografías que propone aguja

**Comment by aguja2013** [comment]
Podemos probar... con respecto a los iconos podemos convertir los que gonzo puso en el mockup o buscar ya hechos. A mi me gustan los que están. Los pasamos a svg y los convertimos en icomoon.

**Comment by andresxg** [comment]
![screenshot 2015-04-28 09 28 49](https://cloud.githubusercontent.com/assets/11749237/7371897/2d666054-ed89-11e4-8c6e-86b562faf06b.png)
escogeré otra tipo

**Comment by slvr** [comment]
puede ser de iconmoon o tambien lo de awesome font :)

**Comment by aguja2013** [comment]
Elegir tipografía para cerrar ya que el milistone caduca hoy!

**Comment by andresxg** [comment]
https://www.google.com/fonts/specimen/Bitter esta es la tipografia, dejo el link para que vean

**Comment by aguja2013** [comment]
ok, dejamos Bitter 400 y 700 para arrancar. Luego vemos durante la marcha si agregamos alguna otra.
cierro issue. ¡Primer Milestone terminado!! Enhorabuena a todos
